name: izoldian

services:
  izoldian:
    container_name: izoldian
    build: .
    restart: unless-stopped
    environment:
      - CORS_ORIGINS=*

      # - HOST=0.0.0.0
      # - PORT=8000
      # - DATA_DIR=/app/data
      # - DB_PATH=/app/data/izoldian.db

      # Authentication
      # - USER_SIGNUP=true
      # - DISABLE_INTERNAL_AUTH=false

      # - OIDC_ENABLED=true
      # - OIDC_ISSUER=https://auth.example.com
      # - OIDC_CLIENT_ID=izoldian
      # - OIDC_CLIENT_SECRET=your-client-secret
      # - OIDC_REDIRECT_URI=http://localhost:8000/api/auth/oidc/callback
      # - OIDC_SCOPES=openid profile email
    volumes:
      - ./data:/app/data
    ports:
      - 8000:8000
