name: izoldian

services:
  izoldian:
    container_name: izoldian
    image: ghcr.io/roman-kvasnikov/izoldian:latest
    restart: unless-stopped
    user: 1000:1000
    environment:
      - CORS_ORIGINS=*

      # - HOST=0.0.0.0
      # - PORT=8000
      # - DATA_DIR=/app/data
      # - DB_PATH=/app/data/izoldian.db
      # - SESSION_MAX_AGE_DAYS=7

      # Authentication
      # - USER_SIGNUP=true
      # - DISABLE_INTERNAL_AUTH=false

      # - OIDC_ENABLED=true
      # - OIDC_ISSUER=https://auth.example.com
      # - OIDC_CLIENT_ID=izoldian
      # - OIDC_CLIENT_SECRET=your-client-secret
      # - OIDC_REDIRECT_URI=http://localhost:8000/api/auth/oidc/callback
      # - OIDC_SCOPES=openid profile email
    volumes:
      - ./data:/app/data
    ports:
      - 8000:8000
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
    deploy:
      resources:
        limits:
          memory: 512M
